In [95]:
import numpy as np

In [96]:
#question - 1

In [97]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]],np.uint16)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [98]:
arr.shape #shape of array

(4, 2)

In [99]:
arr.ndim #dimensions of array

2

In [100]:
arr.itemsize #number of bytes of each item

2

In [101]:
#question - 2

In [102]:
arr1 = np.arange(1,100,10).reshape(5,2)
arr1

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])

In [103]:
arr1.shape

(5, 2)

In [104]:
#question - 3

In [105]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [106]:
print(sampleArray[:,1])

[22 55 88]


In [107]:
#question - 4

In [108]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [114]:
sampleArray[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [115]:
#question - 5

In [116]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]]) 
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]]) 

In [117]:
res_arr = arrayOne + arrayTwo
print(res_arr)

[[20 39 33]
 [25 25 28]]


In [118]:
sq_arr = res_arr ** 2
print(sq_arr)

[[ 400 1521 1089]
 [ 625  625  784]]


In [119]:
#question - 7

In [120]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [75]:
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [121]:
sampleArray[sampleArray[1,:].argsort()]

array([[53, 94, 66],
       [82, 22, 12],
       [34, 43, 73]])

In [138]:
import pandas as pd

In [139]:
#question - 6

In [173]:
file = 'Automobile_data.csv'
Df = pd.read_csv(file)

In [175]:
Df[Df['price'] == Df['price'].max()]['company']

35    mercedes-benz
Name: company, dtype: object

In [176]:
#question - 7

In [177]:
Df.groupby('company')['price'].max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [178]:
#question - 8

In [179]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]} 
JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [180]:
df1 = pd.DataFrame.from_dict(GermanCars)
df2 = pd.DataFrame.from_dict(JapaneseCars)

In [181]:
Df = pd.concat([carsDf1, carsDf2], keys=["Germany", "Japan"])
Df

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

In [182]:
#question - 9

In [184]:
Df.sort_values('Price')

Company   Price
Japan   1        Honda   23600
Germany 0         Ford   23845
Japan   0       Toyota   29995
        3  Mitsubishi    58900
        2       Nissan   61500
Germany 3         Audi   71400
        2          BMV  135925
        1     Mercedes  171995

In [185]:
#question - 10

In [186]:
df

Germany  Company             [Ford, Mercedes, BMV, Audi]
         Price            [23845, 171995, 135925, 71400]
Japan    Company    [Toyota, Honda, Nissan, Mitsubishi ]
         Price              [29995, 23600, 61500, 58900]
dtype: object

In [187]:
df1['Company'].value_counts()

BMV         1
Ford        1
Mercedes    1
Audi        1
Name: Company, dtype: int64