In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.16.5


In [4]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\Mansi Saxena\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
[np.ones(9).reshape(3,3) == 1]

[array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])]

In [7]:
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr = np.arange(10)
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [9]:
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
narr = arr.copy()
narr[arr%2 == 1]= -1
narr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
#question  - 6 - DOUBT

In [12]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out
#> [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
np.arange(1,4)

array([1, 2, 3])